# Generated by Django 2.1.4 on 2024-05-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='subject',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='password',
        ),
    ]
