# Generated by Django 2.1.4 on 2024-05-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_message_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoring_time', models.DateTimeField()),
                ('water_quality_category', models.CharField(max_length=10)),
                ('water_temperature', models.FloatField()),
                ('pH', models.FloatField()),
                ('dissolved_oxygen', models.FloatField()),
                ('conductivity', models.FloatField()),
                ('turbidity', models.FloatField()),
                ('permanganate_index', models.FloatField()),
                ('ammonia_nitrogen', models.FloatField()),
                ('total_phosphorus', models.FloatField()),
                ('total_nitrogen', models.FloatField()),
                ('site_status', models.CharField(max_length=20)),
            ],
        ),
    ]
