# Generated by Django 2.1.4 on 2024-06-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_water_quality_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phone_number',
            field=models.CharField(default='123456789', max_length=200),
        ),
    ]
