# Generated by Django 2.1.4 on 2024-05-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240523_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterqualitydata',
            name='monitoring_time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
