# Generated by Django 2.1.4 on 2024-05-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_waterqualitydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterqualitydata',
            name='ammonia_nitrogen',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitydata',
            name='conductivity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitydata',
            name='dissolved_oxygen',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitydata',
            name='monitoring_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitydata',
            name='pH',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitydata',
            name='permanganate_index',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitydata',
            name='site_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitydata',
            name='total_nitrogen',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitydata',
            name='total_phosphorus',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitydata',
            name='turbidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitydata',
            name='water_quality_category',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitydata',
            name='water_temperature',
            field=models.FloatField(null=True),
        ),
    ]
